apiVersion: v1
kind: Service
metadata:
  labels:
    app: certmanager-app
  name: certmanager-app-service
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  selector:
    app: certmanager-app
  type: LoadBalancer
